server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "postgres"
  port: 5432
  user: "dns_collector"
  password: "dns_collector_pass"
  database: "dns_collector"
  ssl_mode: "disable"

logging:
  level: "info"

cors:
  allowed_origins:
    - "http://localhost:8080"
    - "http://localhost:5173"
  allow_credentials: true
